### ISSUE TITLE
✨ [FEAT] 스프링 초기 세팅

### ISSUE THREAD

**Issue by jinho7** [jinho7/UMC_SmuPool_GroupD_BE#1]
## 📝 개요
- 스프림 초기 세팅
- JAVA 17
- SpringBoot  3.2.5

## ✔️ To-Do
- [x] applicaiton.yml 작성
- [x] 필요한 의존성 추가 (DB, JWT, Redis, Swagger, WebSocket 등)
- [x] ISSUE 템플릿 작성
- [x] PR 템플릿 작성

## 👀 ETC
- 

## ⏰ 예상 소요 시간
- 즉시
